config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  devise_for :users
  resources :users
  resources :orders
  resources :products
  resources :arrivals
  resources :prescriptions
  get 'home/index'

  root 'home#index'

  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  enum for_adult_children: [ :for_adult, :for_children ]

  belongs_to :doctor, class_name: 'User'
  has_one :product

  validates :number, presence: true, uniqueness: true, format: { with: /^РЛ\d{6}$/, message: "Укажіть коректний номер рецепта, н.п.РЛ123456", :multiline => true}
  validates :for_adult_children, inclusion: { in: Prescription.for_adult_children.keys }
  validate :expiry_date_is_in_the_future

  def expiry_date_is_in_the_future
    if !expiry_date.present? || expiry_date <= Date.today
      errors.add(:expiry_date, "Укажіть коректний термін придатності.")
    end
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]
  before_action :authorize_prescription!

  def index
    @prescriptions = policy_scope(Prescription)
                       .joins('inner join products on prescriptions.product_id = products.id')
                       .joins('inner join users on prescriptions.doctor_id = users.id')
                       .select('prescriptions.*, products.name as product_name, users.name as doctor_name')
  end

  def show
  end

  def new
    @prescription = Prescription.new
  end

  def edit
  end

  def create
    @prescription = Prescription.new(prescription_params)
    fill_new_prescription_by_defaults

    if @prescription.save
      redirect_to @prescription, notice: 'Рецепт був успішно створений.'
    else
      render :new
    end
  end

  def update
    if @prescription.update(prescription_params)
      redirect_to @prescription, notice: 'Рецепт був успішно оновлений.'
    else
      render :edit
    end
  end

  def destroy
    @prescription.destroy
    redirect_to prescriptions_url, notice: 'Рецепт був успішно видалений.'
  end

  private

  def set_prescription
    @prescription = Prescription.joins('inner join products on prescriptions.product_id = products.id')
                                .joins('inner join users on prescriptions.doctor_id = users.id')
                                .select('prescriptions.*, products.name as product_name, users.name as doctor_name')
                                .find(params[:id])
  end

  def prescription_params
    params.require(:prescription).permit(:number, :product_id, :expiry_date)
  end

  def fill_new_prescription_by_defaults
    @prescription.is_used = false
    @prescription.doctor_id = current_user.id
    @prescription.for_adult_children = Product.find(@prescription.product_id).for_adult_children
  end

  def authorize_prescription!
    authorize(@prescription || Prescription)
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= form_with(model: prescription) do |form| %>
  <% if prescription.errors.any? %>
    <%= render partial: 'shared/record_errors', locals: {errors: prescription.errors} %>
  <% end %>

  <div class="field">
    <%= form.label "Номер", {:class => "lbl"} %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label "Ліки", {:class => "lbl"} %>
    <% list_prescriptions = Product.require_prescription.ordered_by_name.map {|key| [key.name, key.id]} %>
    <%= form.select :product_id, options_for_select(list_prescriptions, form.object.product_id) %>
  </div>

  <div class="field">
    <%= form.label "Термін придатності", {:class => "lbl"} %>
    <%= form.text_field :expiry_date, type: :date %>
  </div>

  <div class="actions">
    <%= form.submit "Зберегти" %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<%= provide :page_title, "Рецепт №#{@prescription.number}" %>
<h1>Редагування рецепту</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Показати', @prescription %> |
<%= link_to 'Назад', prescriptions_path %>

app/views/prescriptions/index.html.erb
<%= provide :page_title, 'Рецепти' %>

<h1>Рецепти</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th>Термін придатності</th>
      <th>Використаний</th>
      <th>Лікар</th>
      <th>Ліки</th>
      <th>Для дорослих/дітей</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td><%= prescription.number %></td>
        <td><%= date_fmt(prescription.expiry_date, true) %></td>
        <td><%= check_mark_fmt(prescription.is_used) %></td>
        <td><%= prescription.doctor_name %></td>
        <td><%= prescription.product_name %></td>
        <td><%= for_whom_fmt(prescription.for_adult_children) %></td>
        <td><%= link_to 'Показати', prescription %></td>
        <td><%= link_to 'Редагувати', edit_prescription_path(prescription) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Створити рецепт', new_prescription_path %> |
<%= link_to "Назад", :back %>

app/views/prescriptions/new.html.erb
<%= provide :page_title, 'Створення нового рецепта' %>
<h1>Створення нового рецепта</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Назад', prescriptions_path %>

app/views/prescriptions/show.html.erb
<%= provide :page_title, "Рецепт №#{@prescription.number}" %>

<p>
  <strong>Номер:</strong>
  <%= @prescription.number %>
</p>
<p>
  <strong>Термін придатності:</strong>
  <%= date_fmt(@prescription.expiry_date, true) %>
</p>

<p>
  <strong>Використаний:</strong>
  <%= bool_fmt(@prescription.is_used) %>
</p>

<p>
  <strong>Лікар:</strong>
  <%= @prescription.doctor_name %>
</p>

<p>
  <strong>Ліки:</strong>
  <%= @prescription.product_name %>
</p>

<p>
  <strong>Для дорослих/дітей:</strong>
  <%= for_whom_fmt(@prescription.for_adult_children) %>
</p>

<% if policy(@prescription).edit? %>
  <%= link_to 'Редагувати', edit_prescription_path(@prescription) %> |
<% end %>
<%= link_to 'Назад', prescriptions_path %>