config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  devise_for :users
  resources :users
  resources :orders
  resources :products
  resources :arrivals
  resources :prescriptions
  get 'home/index'

  root 'home#index'

  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/arrival.rb
class Arrival < ApplicationRecord
  has_one :product

  validates :qty, :numericality => { :greater_than_or_equal_to => 0 }
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/arrivals_controller.rb
class ArrivalsController < ApplicationController
  before_action :set_arrival, only: [:show, :edit, :update, :destroy]
  before_action :authorize_arrival!

  def index
    @arrivals = Arrival.joins('inner join products on arrivals.product_id = products.id')
                       .select('arrivals.*, products.name as product_name')
  end

  def show
  end

  def new
    @arrival = Arrival.new
  end

  def edit
  end

  def create
    @arrival = Arrival.new(arrival_params)
    if @arrival.save
      StockManager.change_qty(@arrival.product_id, @arrival.qty)
      redirect_to @arrival, notice: 'Надходження було успішно збережене.'
    else
      render :new
    end
  end

  def update
    if @arrival.update(arrival_params)
      redirect_to @arrival, notice: 'Arrival was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @arrival.destroy
    redirect_to arrivals_url, notice: 'Arrival was successfully destroyed.'
  end

  private

  def set_arrival
    @arrival = Arrival.joins('inner join products on arrivals.product_id = products.id')
                      .select('arrivals.*, products.name as product_name')
                      .find(params[:id])
  end

  def arrival_params
    params.fetch(:arrival, {}).permit([:product_id, :price, :qty])
  end

  def authorize_arrival!
    authorize(@arrival || Arrival)
  end
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
end

app/views/arrivals/_form.html.erb
<%= form_with(model: arrival) do |form| %>
  <% if arrival.errors.any? %>
    <%= render partial: 'shared/record_errors', locals: {errors: arrival.errors} %>
  <% end %>

  <div class="field">
    <%= form.label "Ліки", {:class => "lbl"} %>
    <%= form.select :product_id, options_for_select(Product.all.map {|key| [key.name, key.id]}, form.object.product_id) %>
  </div>

  <div class="field">
    <%= form.label "Кількість", {:class => 'lbl'} %>
    <%= form.number_field :qty, value: form.object.qty.to_i || 1, step: 1 %>
  </div>

  <div class="field">
    <%= form.label "Ціна", {:class => 'lbl'} %>
    <%= form.number_field :price, value: number_to_currency(form.object.price.to_f, delimiter: '', unit: ''), step: :any %>
  </div>

  <div class="actions">
    <%= form.submit "Зберегти" %>
  </div>
<% end %>

app/views/arrivals/edit.html.erb
<%= provide :page_title, "Надходження №#{@arrival.id}" %>
<h1>Редагування надходження<%= " №#{@arrival.id}" %></h1>

<%= render 'form', arrival: @arrival %>

<%= link_to 'Показати', @arrival %> |
<%= link_to 'Назад', arrivals_path %>

app/views/arrivals/index.html.erb
<%= provide :page_title, 'Надходження' %>

<h1>Надходження</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th>Дата</th>
      <th>Ліки</th>
      <th>Кількість</th>
      <th>Ціна</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @arrivals.each do |arrival| %>
      <tr>
        <td><%= arrival.id %></td>
        <td><%= date_fmt(arrival.created_at) %></td>
        <td><%= arrival.product_name %></td>
        <td><%= arrival.qty %></td>
        <td><%= price_fmt(arrival.price) %></td>
        <td><%= link_to 'Показати', arrival %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(Arrival).create? %>
  <%= link_to 'Створити надходження', new_arrival_path %> |
<% end %>
<%= link_to 'Назад', :back %>

app/views/arrivals/new.html.erb
<%= provide :page_title, 'Створення нового надходження' %>
<h1>Нове надходження</h1>

<%= render 'form', arrival: @arrival %>

<%= link_to 'Назад', arrivals_path %>

app/views/arrivals/show.html.erb
<%= provide :page_title, "Надходження №#{@arrival.id}" %>

<p>
  <strong>Номер:</strong>
  <%= @arrival.id %>
</p>

<p>
  <strong>Дата:</strong>
  <%= date_fmt(@arrival.created_at) %>
</p>

<p>
  <strong>Ліки:</strong>
  <%= @arrival.product_name %>
</p>

<p>
  <strong>Кількість:</strong>
  <%= @arrival.qty %>
</p>

<p>
  <strong>Ціна:</strong>
  <%= price_fmt(@arrival.price) %>
</p>

<% if policy(@arrival).edit? %>
  <%= link_to 'Редагувати', edit_arrival_path(@arrival) %> |
<% end %>
<%= link_to 'Назад', arrivals_path %>