config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  devise_for :users
  resources :users
  resources :orders
  resources :products
  resources :arrivals
  resources :prescriptions
  get 'home/index'

  root 'home#index'

  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-lg-start fixed-bottom footer">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    &copy <%= Time.now.year %> Copyright:
    <a class="text-dark" href="mailto:saintcoder@gmail.com">slashdev</a>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-light bg-light navbar-expand-sm">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <img
          src="<%= asset_path('drugs.png') %>"
          class="me-2"
          height="20"
          alt="PharmacyRi2022 Logo"
          loading="lazy"
          />
        <small>PharmacyRi2022</small>
      </a>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Ліки", products_url, {:class => 'nav-link'} %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Замовлення", orders_path, {:class => 'nav-link'} %>
          </li>
        <% end %>
        <% if user_signed_in? && current_user.is_doctor? %>
          <li class="nav-item">
            <%= link_to "Рецепти", prescriptions_path, {:class => 'nav-link'} %>
          </li>
        <% end %>
        <% if user_signed_in? && current_user.is_pharmacist? %>
          <li class="nav-item">
            <%= link_to "Надходження", arrivals_path, {:class => 'nav-link'} %>
          </li>
        <% end %>
        <% if user_signed_in? && current_user.is_admin? %>
          <li class="nav-item">
            <%= link_to "Користувачі", users_path, {:class => 'nav-link'} %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Про цей застосунок", about_index_path, {:class => 'nav-link'} %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Профайл (#{current_user.name})", current_user, {:class => 'nav-link'} %>
          </li>
          <li class="nav-item">
            <%= link_to 'Вийти', destroy_user_session_path, method: :delete, data: { confirm: 'Ви певні?' }, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Зареєструватись', new_user_registration_path, {:class => 'nav-link'} %>
          </li>
          <li class="nav-item">
            <%= link_to 'Увійти', new_user_session_path, {:class => 'nav-link'} %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_record_errors.html.erb
<div class="alert alert-danger">
  <%= "#{errors.count} помилки(-а)" %> заважають збереженню:
  <ul>
    <% errors.each do |error| %>
      <li class="alert-item"><%= error.message %></li>
    <% end %>
  </ul>
</div>