config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  devise_for :users
  resources :users
  resources :orders
  resources :products
  resources :arrivals
  resources :prescriptions
  get 'home/index'

  root 'home#index'

  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/product.rb
class Product < ApplicationRecord
  enum for_adult_children: [ :for_adult, :for_children ]

  has_many :order_detail

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 300 }
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }
  validates :for_adult_children, inclusion: { in: Product.for_adult_children.keys }

  scope :on_stock, -> { joins('INNER JOIN stock ON products.id = stock.product_id')
                          .where('stock.qty - stock.reserve_qty > 0') }
  scope :with_stock, -> { joins('LEFT JOIN stock ON products.id = stock.product_id')
                            .select('products.*, coalesce(stock.qty, 0) - coalesce(stock.reserve_qty, 0) available_qty') }
  scope :ordered_by_name, -> { order(name: :asc) }
  scope :require_prescription, -> { where(required_prescription: true) }

  def self.get_for_adult_children_array
    for_adult_children.map {|key, value| [key.titleize, Product.for_adult_children.key(value)]}
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize_product!

  def index
    @products = Product.with_stock.ordered_by_name
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Ліки були успішно створені.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Ліки були успішно оновлені.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Ліки були успішно видалені.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.fetch(:product, {}).permit(:name, :price, :required_prescription, :for_adult_children, :description, :img_url)
  end

  def authorize_product!
    authorize(@product || Product)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <%= render partial: 'shared/record_errors', locals: {errors: product.errors} %>
  <% end %>

  <div class="field">
    <%= form.label "Назва", {:class => 'lbl'} %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "Опис", {:class => 'lbl va-top'} %>
    <%= form.text_area(:description, size: '60x6') %>
  </div>

  <div class="field">
    <%= form.label "Посиляння на фото", {:class => 'lbl'} %>
    <%= form.text_field :img_url %>
  </div>

  <div class="field">
    <%= form.label "Потребує рецепту", {:class => 'lbl'} %>
    <%= form.check_box :required_prescription %>
  </div>

  <div class="field">
    <%= form.label "Ціна", {:class => 'lbl'} %>
    <%= form.number_field :price, value: number_to_currency(form.object.price.to_f, delimiter: '', unit: ''), step: :any %>
  </div>

  <div class="field">
    <%= form.label "Для дорослих/дітей", {:class => 'lbl'} %>
    <%= form.select :for_adult_children, options_for_select(Product.get_for_adult_children_array, product.for_adult_children) %>
  </div>

  <div class="actions">
    <%= form.submit "Зберегти" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= provide :page_title, @product.name %>
<h1>Редагування ліки</h1>

<%= render 'form', product: @product %>

<%= link_to 'Показати', @product %> |
<%= link_to 'Назад', products_path %>

app/views/products/index.html.erb
<%= provide :page_title, 'Ліки' %>

<h1>Ліки</h1>

<table>
  <thead>
    <tr>
      <th>Назва</th>
      <th>Ціна</th>
      <th>Потребує рецепт</th>
      <th>Для дорослих/дітей</th>
      <th>Залишок</th>
    </tr>
  </thead>

  <tbody>
    <% user_is_pharmacist = user_signed_in? && current_user.is_pharmacist? %>
    <% @products.each do |product| %>
      <tr onclick="document.location = '<%= product_path(product) %>'" class="pointer">
        <td><%= product.name %></td>
        <td><%= price_fmt(product.price) %></td>
        <td><%= check_mark_fmt(product.required_prescription) %></td>
        <td><%= for_whom_fmt(product.for_adult_children) %></td>
        <td><%= user_is_pharmacist ? product.available_qty : available_qty_fmt(product.available_qty) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(Product).create? %>
  <%= link_to 'Створити ліки', new_product_path %> |
<% end %>
<%= link_to 'Назад', :back %>

<% if user_signed_in? && current_user.is_pharmacist?  %>
  <hr>
  <h3>Графік кількості замовлень ліків по датам:</h3>
  <% prepared_data = Order.group_by_day(:created_at).count %>
  <%= line_chart prepared_data, donut: true %>

  <br>

  <h3>Графік продажу ліків по назвам, в грн:</h3>
  <% prepared_data = OrderDetail.joins('inner join products as p on order_details.product_id = p.id')
                                .select('p.name as name, order_details.qty * order_details.price as amount')
                                .group('name').sum('order_details.qty * order_details.price') %>
  <%= bar_chart prepared_data %>
<% end%>

app/views/products/new.html.erb
<%= provide :page_title, 'Створення нової ліки' %>
<h1>Створення нової ліки</h1>

<%= render 'form', product: @product %>

<%= link_to 'Назад', products_path %>

app/views/products/show.html.erb
<%= provide :page_title, @product.name %>

<p>
  <strong>Назва:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Опис:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Ціна:</strong>
  <%= price_fmt(@product.price) %>
</p>

<p>
  <strong>Потребує рецепту:</strong>
  <%= bool_fmt(@product.required_prescription) %>
</p>

<p>
  <strong>Для дорослих/дітей:</strong>
  <%= for_whom_fmt(@product.for_adult_children) %>
</p>

<% if policy(@product).edit? %>
  <%= link_to 'Редагувати', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Назад', products_path %>